
export const CREATE_MOVIE = "CREATE_MOVIE"
export const DELETE_MOVIE = "DELETE_MOVIE"
export const UPDATE_MOVIE = "UPDATE_MOVIE"
export const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES"
export const FETCH_MOVIE_BY_ID = "FETCH_MOVIE_BY_ID"
export const FETCH_MOVIE_BY_GENRES= "FETCH_MOVIE_BY_GENRES"

export const CREATE_REVIEW= "CREATE_REVIEW"
export const GET_REVIEWS= "GET_REVIEWS"
export const DELETE_REVIEW= "DELETE_REVIEW"

export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"

export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"